run:
  device: 'cuda'
  writer_dir: 'runs/ham10000'

model:
  save_dir: 'checkpoints/ham10000'
  name: 'miss_ham10000'
  class: 'MissFormer'  # options: UNet, AttentionUNet, DeepLabV3Plus, TransUNet
  params: {}

dataset:
  input_size: 128
  name: "ham10000"
  class_name: "HAM10000DatasetFast" # do not change it unless you implement a new. this <Fast> class loads all files into ram at once to speed up data loading.
  data_dir: "/mnt/mmlab2024nas/danh/hoangdv/ham10000" # inside of this folder must exist <images> and <masks> folders. Inside of this folder the required numpy files will create inside of <np> folder.
  number_classes: 2
  img_channels: 3
  msk_channels: 1

data_loader:
  train:
    batch_size: 16
    shuffle: true
    pin_memory: true
  validation:
    batch_size: 16
    shuffle: false
    pin_memory: true
  test:
    batch_size: 16
    shuffle: false
    pin_memory: false

training:
  epochs: 300
  optimizer:
    name: 'SGD'
    params:
      lr: 0.01
      weight_decay: 0.0001
  scheduler:
    factor: 0.5
    patience: 10
    verbose: true
  supervised_loss:
    name: 'bce'
    params:
      bce_weight: 1.0

augmentation:
  p: 0.7
  levels:
    pixel:
      p: 1.0
      transforms: {}
    spacial:
      p: 1.0
      transforms: {}

testing:
  ensemble: 1
  model_weigths:
    overload: false
    file_path: ""
  result_imgs:
    save: true
    dir: "/mnt/mmlab2024nas/danh/hoangdv/LiteDermoSegDiff/HAM10000/image/missformer"
